### PR TITLE
Add missing QStringList::replaceInStrings method

### PR DESCRIPTION
**Pull request by Montel**

### CODE REVIEW

**Review by ahayzen-kdab — APPROVED** [review]
Looks good, note the commit name is wrong it should be `QStringList::replaceInStrings` not `QString::` ?

**Comment by Montel** [comment]
oops indeed :) I will fix commit message

**Comment by ahayzen-kdab** [comment]
It is fixed in the commit message, but the pull request has it's own name :-)

**Review by ahayzen-kdab — APPROVED** [review]
LGTM :-)

**Pull request merged**
