### PR TITLE
try enabling tests on Windows

### PR DESCRIPTION
**Pull request by Be-ing**
Maybe #105 fixed the link errors?

### CODE REVIEW

**Comment by Be-ing** [comment]
Well that didn't work. I still don't know what's going wrong with those link errors.

**Comment by LeonMatthesKDAB** [comment]
Just a random thought: We're in some places defining `extern "C"` functions that take references as arguments.

GCC has been warning about this for a while, as C doesn't have references, and we'd technically have to use pointers.
Maybe this is related somehow?

**Comment by Be-ing** [comment]
I don't see any compile warnings from GCC using GCC 11.2.1 locally on Fedora 35 nor on the Ubuntu CI.

**Comment by ahayzen-kdab** [comment]
IIRC the warnings were actually from clang and hence why we used to have this warning disable https://github.com/KDAB/cxx-qt/blob/3828f36202ee2edba3e7cf418449e444ac6c61ba/cxx-qt-gen/src/cxx_qt.cpp#L42

The Windows issues appear to be maybe linker related but it'll probably be more obvious on an actual machine than trying to fight CI, we just need to spend some time investigating what is missing/wrong.

**Comment by ahayzen-kdab** [comment]
> Can this be closed? We have Windows CI now, don't we?

We don't there are problems ... 
- QML tests aren't being run
- Cargo tests aren't being run
- For me the examples crash on exit but not for Be (maybe a MSVC 2019 vs 2022 thing or something has fixed it)

**Comment by Be-ing** [comment]
We still need to figure out what to do about adding Qt to PATH to fix the DLL not found errors when running the tests... or figure out some hack around #224.

**Comment by Be-ing** [comment]
However, the link errors with the tests have been fixed since overhauling the build system to compile the generated C++ with Cargo. The remaining issues are setting the required environment variables at runtime.

**Comment by ahayzen-kdab** [comment]
@Be-ing this can be closed now as there are working Windows tests? :tada:

**Comment by Be-ing** [comment]
Yes superseded  by #500

**Pull request closed without merging**
