### PR TITLE
cxx-qt-gen: add support for multiple QObjects in writer/cpp

### PR DESCRIPTION
**Pull request by ahayzen-kdab**

### CODE REVIEW

**Comment by ahayzen-kdab** [comment]
This assumes that one module block will result in one C++ header file (which i believe will always be true?).

Our other debates are whether the module or file name should be used for the resultant files, so then that would determine if multiple module blocks result in multiple C++ header files or a single header file. However for now we only support one module per file anyway (and also one QObject per module, but that may change sooner)

**Comment by ahayzen-kdab** [comment]
For now this can be draft as the Rust side needs figuring out in the CXX bridge to avoid collisions.

**Comment by ahayzen-kdab** [comment]
See in #157 under "Support multiple QObject's being defined in one block" why the Rust side of this is blocked.

**Review by LeonMatthesKDAB — APPROVED** [review]
LGTM

**Pull request merged**
