### PR TITLE
cmake: set MSVC_RUNTIME_LIBRARY to MultiThreadedDLL

### PR DESCRIPTION
**Pull request by ahayzen-kdab**
Related to #682
Related to #676

### CODE REVIEW

**Comment by OlivierLDff** [comment]
Will it work for more complex projects? Because then you will have target linking to the default, and the app & rust lib to MultiThreadedDLL.
I would recommend setting the global `CMAKE_MSVC_RUNTIME_LIBRARY` so every target do so.

**Comment by ahayzen-kdab** [comment]
> Will it work for more complex projects? Because then you will have other targets linking to the default, and the app & rust lib to MultiThreadedDLL. Not sure if this is how it work. I would recommend setting the global `CMAKE_MSVC_RUNTIME_LIBRARY` so every target do so.

Can we set this in all of the example CMakeLists.txt's ? I know it's slightly pointless as it should come from the route. But we see people copy the CMakeList out of the example folder and then miss that there is something set globally. So i think there should be something in each of the projects too.

I'm also trying to fix my Windows setup so i can test some of this stuff myself :sweat_smile:

**Comment by OlivierLDff** [comment]
Yes setting it in each example is a good idea, maybe with a warning that it would be best to set it in the command line.

**Comment by ahayzen-kdab** [comment]
This seems to work :-)

@OlivierLDff does the change look sane to you ?

**Review by vimpostor — APPROVED** [review]

**Pull request merged**
