### PR TITLE
cxx-qt-lib: Display and Debug for QString

### PR DESCRIPTION
**Pull request by Ayush1325**
Implement Display and Debug for QString. 

I think at least Debug is a fairly common thing that should be implemented for all the types in cxx-qt-lib.

### CODE REVIEW

**Comment by ahayzen-kdab** [comment]
Thanks for pushing this change!

Yes I think we should implement Display / Debug for our Qt types, we have an issue to add Default #53 and Serde (Serialize/Deserialize) #16. I have added Display / Debug to the #53 issue so we can track it.

For QString itself this is an interesting one, as since #69 we now transparently wrap opaque types (note this is not in a tagged release yet). What this means is that for the opaque types I don't think the developer will ever need to know that `QStringCpp` exists? They will only be using `String` ? As since that change `String` is used as the return type and `&str` can be used as the input type.

So I'm not sure that this is useful for `QStringCpp` or the other `*Cpp` types? I think it'd be more useful for the type used by the developer - eg QPoint or QColor (not QColorCpp) etc (unless i'm forgetting some use case :-) )

**Comment by Ayush1325** [comment]
> Thanks for pushing this change!
> 
> Yes I think we should implement Display / Debug for our Qt types, we have an issue to add Default #53 and Serde (Serialize/Deserialize) #16. I have added Display / Debug to the #53 issue so we can track it.
> 
> For QString itself this is an interesting one, as since #69 we now transparently wrap opaque types (note this is not in a tagged release yet). What this means is that for the opaque types I don't think the developer will ever need to know that `QStringCpp` exists? They will only be using `String` ? As since that change `String` is used as the return type and `&str` can be used as the input type.
> 
> So I'm not sure that this is useful for `QStringCpp` or the other `*Cpp` types? I think it'd be more useful for the type used by the developer - eg QPoint or QColor (not QColorCpp) etc (unless i'm forgetting some use case :-) )

Well, in the example in the book, the invocable function takes `&QString` as input which is then converted to string. That was why I decided to implement `Debug` and `Display` for it. However, the examples in the /examples folder have `&str` inputs for such parameters so I guess this is no longer needed.

**Comment by ahayzen-kdab** [comment]
> Well, in the example in the book, the invocable function takes `&QString` as input which is then converted to string.

Right, the book shows the last the tagged version of the code (eg what a developer would be using from crates.io), unfortunately this area has already changed in `main` so when the next version is tagged (eg 0.3) then the book will show how `&QString` isn't used any more.

I still think these changes are valid for other types though, eg QPoint, QColor etc as they don't use a std Rust type.

**Comment by Ayush1325** [comment]
I am thinking of closing the pull request now since this doesn't seem required.

**Pull request closed without merging**
