### PR TITLE
Add make_shared template

### PR DESCRIPTION
**Pull request by Montel**

### CODE REVIEW

**Comment by LeonMatthesKDAB** [comment]
See: #823

**Review by LeonMatthesKDAB — APPROVED** [review]
LGTM. I assume you tested this works as expected?

**Comment by LeonMatthesKDAB** [comment]
@Montel I think this can be merged now?

**Comment by ahayzen-kdab** [comment]
Once we have #843 I wonder if we move these into a `cxx-qt` header, so `cxx-qt-common` / `cxx-qt`

**Pull request merged**
