### PR TITLE
Enable verbose ctest output

### PR DESCRIPTION
**Pull request by LeonMatthesKDAB**
This could help investigate why CTest is slow on Windows

### CODE REVIEW

**Comment by LeonMatthesKDAB** [comment]
So it seems the issue with Windows is indeed that building before `cargo test` takes around 6 min.
This is very strange, as the build with CMake just takes 2 min. So why does building from within ctest all of a sudden take three times as long?
It almost seems as if compiler caching isn't working there anymore?

**Comment by ahayzen-kdab** [comment]
> So it seems the issue with Windows is indeed that building before `cargo test` takes around 6 min. This is very strange, as the build with CMake just takes 2 min. So why does building from within ctest all of a sudden take three times as long? It almost seems as if compiler caching isn't working there anymore?

Are we hitting that `cargo` and `cmake` build into different directories so then you get duplicated `/target` folders and therefore it needs to build everything again ? (I have this problem locally sometimes)

**Comment by ahayzen-kdab** [comment]
@LeonMatthesKDAB do you still need this ? or can it be closed ?

**Comment by ahayzen-kdab** [comment]
Not needed anymore :-)

**Pull request closed without merging**
